apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-classifier
spec:
  selector:
    matchLabels:
      app: pet-classifier
  template:
    metadata:
      labels:
        app: pet-classifier
    spec:
      containers:
      - name: pet-classifier
        image: 081827876616.dkr.ecr.us-east-1.amazonaws.com/pet-classifier:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
